config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "/users", to: "users#index"
  # get "/users/:id", to: "users#show"
  
  root "users#index"

  resources :users

  post "/uploads" , to: "users#upload"


  devise_for :users, controllers: { sessions: 'users/sessions' }


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_one :user_detail , dependent: :destroy
    validates :username, presence: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :username, uniqueness: true
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user
  validates :dob, presence: true
  validate :age_greater_than_18?

  def age_greater_than_18?
    temp_dob = dob.to_s.split('-')
    if dob > 18.years.ago
      errors.add(:dob, "age must be greater than 18")
    end
  end
end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def twitter
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  def passthru
    super
  end

  # GET|POST /users/auth/twitter/callback
  def failure
    super
  end

  protected

  # The path used when OmniAuth fails
  def after_omniauth_failure_path_for(scope)
    super(scope)
  end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  # protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
require 'csv'
class UsersController < ApplicationController
 # before_action :authenticate_admin!

  def index
    @users = User.order('created_at DESC').paginate(page: params[:page])    
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
    
  def create
    @user = User.new(user_params)
    if  @user.save
      user_detail = user_detail_params
      user_detail["user_id"] = @user.id
      @user_detail = UserDetail.new(user_detail)
      if @user_detail.save
        redirect_to @user
      else
        if @user.errors
          flash["alert"]  = @user.errors.full_messages.to_sentence
        end
        if @user_detail.errors
          flash["age"] =   @user_detail.errors.full_messages.to_sentence
          @user.destroy
        end
        redirect_to :action => 'new'
      end
    else
      if @user.errors
        flash["alert"]  = @user.errors.full_messages.to_sentence
      end
      redirect_to :action => 'new'
    end
  end

  def destroy
    user = User.find_by(id: params["id"])
    user.destroy
    redirect_to :users
  end
  


  def upload
    Bulk::BulkUpload.new(params[:picture]).process
    redirect_to :users
  end
    
  def update
    @user = User.find(params[:id])
    @user_detail = UserDetail.find_by(user_id: params[:id])
    if @user.update(user_params) and @user_detail.update(user_detail_params)
      redirect_to :users 
    else 
      flash["user_alert"]  = @user.errors.full_messages.to_sentence
      flash["user_detail_alert"]
      puts @user.errors.full_messages.to_sentence
      redirect_to :action => 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :email)
    end

    def user_detail_params
      params.require(:user_detail).permit(:first_name , :last_name , :dob ,:primary_address , :secondary_address)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
 <div class="nav navbar"> 
  <%= link_to 'Home', root_path%>
  <% if admin_signed_in? %>
    <li><%= link_to current_admin.email, edit_admin_registration_path %></li>
    <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Login', new_admin_session_path , class: "btn-primary" %></li>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Template" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Template" %>">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class='container'>
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<div class = "jumbotron">
<% flash.each do |type, msg| %>  <div class="alert alert-info">    <%= msg %>  </div><% end %>
  <%= form_with  model: user do |user_form| %>
    
    <div class="form-group">
    <%= user_form.label :username, "Username:" %>
    <%= user_form.text_field :username %>
    <% user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>

    <div class="form-group">
    <%= user_form.label :email, "Email:" %>
    <%= user_form.email_field :email %>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>  </div>

    <%= fields_for :user_detail, user.user_detail do |user_detail_form| %>
      
      <div class="form-group">
      <%= user_form.label :query, "First Name:" %>
      <%= user_detail_form.text_field :first_name %>
      </div>
      
      <div class="form-group">
      <%= user_form.label :query, "Last Name:" %>
      <%= user_detail_form.text_field :last_name %>
      </div>
      
      <div class="form-group">
      <%= user_form.label :query, "Primary Address:" %>
      <%= user_detail_form.text_field :primary_address %>
      </div>

      <div class="form-group">
      <%= user_form.label :query, "Secondary Address:" %>
      <%= user_detail_form.text_field :secondary_address %>
      </div>
      
      <div class="form-group">
      <%= user_form.label :query, "DOB:" %>
      <%= user_detail_form.date_field :dob %>
      </div>
    
      <% end %>
    <div class="btn btn-success">
    <%= user_form.submit %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Update User</h1>
<% flash.each do |type, msg| %>  <div class="alert alert-info">    <%= msg %>  </div><% end %>
<div class="jumbotron">
<%= form_with url: "/users/#{@user.id}", method: :put  , model: @user do |user_form| %>
    <div>
    <%= user_form.label :query, "Username:" %>
    <%= user_form.text_field :username %>
    </div>
    <div>
    <%= user_form.label :query, "Email:" %>
    <%= user_form.email_field :email %>
    </div>
    <%= fields_for :user_detail, @user.user_detail do |user_detail_form| %>
      <div>
      <%= user_form.label :query, "First Name:" %>
      <%= user_detail_form.text_field :first_name %>
      </div>
      <div>
      <%= user_form.label :query, "Last Name:" %>
      <%= user_detail_form.text_field :last_name %>
      </div>
      <div>
      <%= user_form.label :query, "Primary Address:" %>
      <%= user_detail_form.text_field :primary_address %>
      </div>
      <div>
      <%= user_form.label :query, "Secondary Address:" %>
      <%= user_detail_form.text_field :secondary_address %>
      </div>
      <%= user_form.label :query, "DOB:" %>
      <%= user_detail_form.date_field :dob %>
    <% end %>
    <div>
      <%= user_form.submit "Update User" , :class => 'btn btn-success'%>
    <div>
  <% end %>
  </div>

app/views/users/index.html.erb
<div class="container jumbotron">
<h2 >Users<%= link_to "New User", new_user_path %></h2>

<%= form_with url: "/uploads", multipart: true do |form| %>
  <%= form.file_field :picture %>
  <%= form.submit "Create multiple users via file upload " %>
<% end %>

<h2>Our Exsisting Users : </h2>


<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>Username</th>
      <th>Email</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th>DOB</th>
      <th>Primary Address</th>
      <th>Secondary Address</th>
    </tr>
  </thead>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.username %></td>
      <td><%= user.email %> </td>
      <td><%= user.user_detail.first_name %> </td>
      <td><%= user.user_detail.last_name %> </td>
      <td><%= user.user_detail.dob %> </td>
      <td><%= user.user_detail.primary_address %> </td>
      <td><%= user.user_detail.secondary_address %> </td>
      <td><%= button_to "Update User", { action: "edit", id: user.id ,  }, { method: :get , class: 'btn btn-primary'} %></td>
      <td><%= button_to "Delete User", { action: "destroy", id: user.id }, method: :delete,class: 'btn btn-danger' ,
       data: { confirm: "Are you sure , you want to delete the user?" } %></td>
      
    </tr>
  <% end %>
</table>

<%= will_paginate @user %>
</div>

app/views/users/new.html.erb
<h2>New User Registration</h2>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<div class="jumbotron">
<h1>Username : <%=  @user.username %></h1>
<p>Email : <%= @user.email %></p>
<p>First Name : <%= @user.user_detail.first_name %> </p>
<p>Last Name : <%= @user.user_detail.last_name %> </p>
<p>DOB :  <%= @user.user_detail.dob %> </p>
<p>Primary Address : <%= @user.user_detail.primary_address %> </p>
<p>Secondary Address : <%= @user.user_detail.secondary_address %> </p>
</div>